language: elixir
opt_release:
  - 18
elixir:
  - 1.0.5
  - 1.0.0

addons:
  postgresql: "9.4"

sudo: false

before_script:
  - psql -c 'create database web_qa_vote_travis_test;' -U postgres
  - cp config/travis.exs config/test.exs
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.create, ecto.migrate

script:
  - mix test

